// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paging.Models;

namespace Paging.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211212105921_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Paging.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Raznovrsne čokolade",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Razni čokoladni bomboni",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "M&M",
                            Price = 3.75m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Voćne žvake",
                            Price = 6.9m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Voćne lizalice",
                            Price = 2.9m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Voćni kiseli bomboni",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Voćne uvezene žvake",
                            Price = 11.9m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kisele žvake",
                            Price = 1.9m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Razni halloween bomboni",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tvrdi voćni bomboni",
                            Price = 9.9m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Razni tvrdi bomboni",
                            Price = 8.97m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tvrdi kiseli bomboni",
                            Price = 5.55m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
