// <auto-generated />
using CandyShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CandyShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CandyShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Čokolade"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Voćni bomboni"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gumeni bomboni"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Halloween bomboni"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tvrdi bomboni"
                        });
                });

            modelBuilder.Entity("CandyShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "Raznovrsne_čokolade",
                            DiscountPercent = 0m,
                            Name = "Raznovrsne čokolade",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "Čokoladni_mix",
                            DiscountPercent = 0m,
                            Name = "Razni čokoladni bomboni",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Code = "Čokoladni_MMS",
                            DiscountPercent = 0m,
                            Name = "M&M",
                            Price = 3.75m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Code = "Voćne_žvake",
                            DiscountPercent = 0m,
                            Name = "Voćne žvake",
                            Price = 6.9m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Code = "Voćne_lizalice",
                            DiscountPercent = 0m,
                            Name = "Voćne lizalice",
                            Price = 2.9m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Code = "Voćni_kiseli",
                            DiscountPercent = 0m,
                            Name = "Voćni kiseli bomboni",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Code = "Uvezene_žvake",
                            DiscountPercent = 0m,
                            Name = "Voćne uvezene žvake",
                            Price = 11.9m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Code = "Kisele_žvake",
                            DiscountPercent = 0m,
                            Name = "Kisele žvake",
                            Price = 1.9m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Code = "Razni_halloween",
                            DiscountPercent = 0m,
                            Name = "Razni halloween bomboni",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Code = "Tvrdi_voćni",
                            DiscountPercent = 0m,
                            Name = "Tvrdi voćni bomboni",
                            Price = 9.9m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Code = "Razni_tvrdi",
                            DiscountPercent = 0m,
                            Name = "Razni tvrdi bomboni",
                            Price = 8.97m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Code = "Tvrdi_kiseli",
                            DiscountPercent = 0m,
                            Name = "Tvrdi kiseli bomboni",
                            Price = 5.55m
                        });
                });

            modelBuilder.Entity("CandyShop.Models.Product", b =>
                {
                    b.HasOne("CandyShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
